### ISSUE TITLE
Gestion de projet - 1h

### ISSUE THREAD

**Issue by LoOTW** [LoOTW/merite#3]
Faire un planning
Etc

Pour le 6 novembre
olivier.blanc@dgfip.finances.gouv.fr

**Comment by mevin15** [comment]
Compte rendu reunion → 
envoie compte rendu a Olivier Blanc 

Recul a prendre sur le projet → estimation des charges 

6 novembre → doc . Quest ce qu’on a  faire ? Quel est la coöprehension projet ? Methodes agiles? Quelle organisation pour le projet ?  Quoi ? Comment ? 
Calendrier d’organisation ? 

Objectif de chacun des cycles ? 
Pas a Noel et dernier cycle terminé avec 10 jours avanr les soutenances 
Reunion au debut et a la fin de chaque cycle : 

competences : comment se partager le travail ? Estimation du temps de realisation 
1ere reunion → faire compte rendu ? 



Olivier Blanc . olivier.blanc@dgfip.finances.gouv.fr principale
oblanc2@gmail.com → pour les drive
