### ISSUE TITLE
Connexion au serveur

### ISSUE THREAD

**Issue by LoOTW** [LoOTW/merite#35]
Connexion par domaine et par pseudo

Implique configuration du réseau en entier (en fixe pour l'instant)

On part sur 3 domaines de 4 utilisateurs

**Comment by mevin15** [comment]
Recuperer codes de herve grall

**Comment by mevin15** [comment]
Estimation temps : 3h

**Comment by hgrall** [comment]
Le dépôt a été mis à jour. Cf. https://github.com/hgrall/merite/tree/master/src/communication/v1m1.
