### ISSUE TITLE
Compte rendu réu fin de sprint 1

### ISSUE THREAD

**Issue by LoOTW** [LoOTW/merite#47]

**Comment by elisaprio** [comment]
https://docs.google.com/document/d/108VGWu9RQjtNvDhVI8HPDbKQcxEX4srxi0rPObCyyCw/edit

**Comment by hgrall** [comment]
Mise à jour de la spécification : cf. structure.org sur le dépôt.
-  https://github.com/hgrall/merite/tree/master/src/communication/v1m1/jeu1_adressageRoutage
